# Generated by Django 5.0.6 on 2026-02-26 18:33

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Room = apps.get_model('rooms', 'Room')
    for room in Room.objects.all():
        room.slug = slugify(room.name)
        room.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bed_type',
            field=models.CharField(blank=True, help_text='e.g. King, Twin, Queen', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description (auto-generated if blank)', max_length=160),
        ),
        migrations.AddField(
            model_name='room',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (auto-generated if blank)', max_length=70),
        ),
        migrations.AddField(
            model_name='room',
            name='room_size',
            field=models.CharField(blank=True, help_text='e.g. 25 sqm', max_length=30),
        ),
        # Step 1: Add slug without unique constraint
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, default=''),
        ),
        # Step 2: Populate slugs from room names
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        # Step 3: Make slug unique
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
