# Generated by Django 5.0.6 on 2026-03-02 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_property_alter_pageseo_page_faq_guest_house_and_more'),
        ('rooms', '0002_room_bed_type_room_meta_description_room_meta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='guest_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.property'),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('guest_house', 'slug')},
        ),
    ]
