# Generated by Django 5.0.6 on 2026-02-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('contact', 'Contact'), ('rooms', 'Rooms'), ('location', 'Guest House in F6/2 Islamabad')], max_length=50, unique=True)),
                ('meta_title', models.CharField(blank=True, help_text='Page title (max 70 chars)', max_length=70)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description (max 160 chars)', max_length=160)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords')),
            ],
            options={
                'verbose_name': 'Page SEO',
                'verbose_name_plural': 'Page SEO',
            },
        ),
        migrations.CreateModel(
            name='SeoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Blue Moon Residency', max_length=100)),
                ('default_meta_title', models.CharField(default='Blue Moon Residency | Best Guest House in F6/2 Islamabad', help_text='Default title for pages without a specific title (max 70 chars)', max_length=70)),
                ('default_meta_description', models.TextField(default='Blue Moon Residency is a top-rated guest house in F-6/2, Islamabad. Comfortable rooms, great service, and prime location near Faisal Mosque. Book now!', help_text='Default meta description (max 160 chars)', max_length=160)),
                ('default_keywords', models.TextField(blank=True, default='guest house islamabad, guest house F6/2, blue moon residency, hotel islamabad, guest house near me, accommodation islamabad, F-6 islamabad hotel', help_text='Comma-separated keywords')),
                ('business_name', models.CharField(default='Blue Moon Residency', max_length=200)),
                ('street_address', models.CharField(default='House # 2-A, Justice Abdul Rasheed Road', max_length=300)),
                ('locality', models.CharField(default='Islamabad', max_length=100)),
                ('region', models.CharField(default='Islamabad Capital Territory', max_length=100)),
                ('postal_code', models.CharField(default='44000', max_length=20)),
                ('country', models.CharField(default='PK', max_length=5)),
                ('phone', models.CharField(blank=True, default='+92-XXX-XXXXXXX', max_length=30)),
                ('email', models.EmailField(blank=True, default='info@bluemoonresidency.com', max_length=254)),
                ('latitude', models.DecimalField(decimal_places=7, default=33.7294, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, default=73.0931, max_digits=10)),
                ('google_maps_embed_url', models.URLField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3318.8!2d73.093!3d33.729!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMzPCsDQzJzQ1LjgiTiA3M8KwMDUnMzUuMiJF!5e0!3m2!1sen!2spk!4v1', help_text='Google Maps embed URL for iframe', max_length=500)),
                ('og_image', models.ImageField(blank=True, help_text='Default Open Graph image (1200x630 recommended)', null=True, upload_to='seo/')),
            ],
            options={
                'verbose_name': 'SEO Settings',
                'verbose_name_plural': 'SEO Settings',
            },
        ),
    ]
