# Generated by Django 5.0.6 on 2026-02-26 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('booking', 'Booking & Payment'), ('rooms', 'Rooms & Amenities'), ('location', 'Location & Transport'), ('policies', 'Policies')], default='general', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NearbyAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('landmark', 'Landmark'), ('shopping', 'Shopping'), ('hospital', 'Hospital'), ('restaurant', 'Restaurant'), ('transport', 'Transport'), ('government', 'Government'), ('education', 'Education')], max_length=20)),
                ('distance', models.CharField(help_text='e.g. 5 min drive, 2 km', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, help_text='e.g. Lahore, Pakistan', max_length=100)),
                ('rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('room_type', models.CharField(blank=True, help_text='e.g. Deluxe Room, Suite', max_length=50)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='seosettings',
            name='check_in_time',
            field=models.CharField(default='14:00', help_text='Check-in time (24h format)', max_length=10),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='check_out_time',
            field=models.CharField(default='12:00', help_text='Check-out time (24h format)', max_length=10),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='currency_symbol',
            field=models.CharField(default='PKR', help_text='Currency symbol shown on site (PKR, Rs., etc.)', max_length=10),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='price_range',
            field=models.CharField(default='PKR 5,000 - 25,000', help_text='Price range for schema markup', max_length=20),
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('contact', 'Contact'), ('rooms', 'Rooms'), ('location', 'Guest House in F6/2 Islamabad'), ('location_islamabad', 'Guest House in Islamabad'), ('location_near_faisal_mosque', 'Guest House Near Faisal Mosque')], max_length=50, unique=True),
        ),
    ]
