# Generated by Django 5.0.6 on 2026-02-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_faq_nearbyattraction_testimonial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seosettings',
            name='booking_com_url',
            field=models.URLField(blank=True, default='', help_text='Booking.com listing URL. If set, "Book Now" buttons will link here instead of the internal booking system. Leave empty to use internal bookings.', max_length=500),
        ),
    ]
