# Generated by Django 5.0.6 on 2026-02-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seosettings_booking_com_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='seosettings',
            name='phone2',
            field=models.CharField(blank=True, default='', help_text='Second contact number (optional)', max_length=30),
        ),
    ]
