# Generated by Django 5.0.6 on 2026-03-02 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seosettings_phone2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('short_name', models.CharField(blank=True, help_text='Short name for UI tabs (e.g. Residency)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('business_name', models.CharField(max_length=200)),
                ('street_address', models.CharField(max_length=300)),
                ('locality', models.CharField(default='Islamabad', max_length=100)),
                ('region', models.CharField(default='Islamabad Capital Territory', max_length=100)),
                ('postal_code', models.CharField(default='44000', max_length=20)),
                ('country', models.CharField(default='PK', max_length=5)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('phone2', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.DecimalField(decimal_places=7, default=33.7294, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, default=73.0931, max_digits=10)),
                ('google_maps_embed_url', models.URLField(blank=True, max_length=500)),
                ('default_meta_title', models.CharField(blank=True, max_length=70)),
                ('default_meta_description', models.TextField(blank=True, max_length=160)),
                ('default_keywords', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='properties/seo/')),
                ('currency_symbol', models.CharField(default='PKR', max_length=10)),
                ('price_range', models.CharField(blank=True, max_length=20)),
                ('check_in_time', models.CharField(default='14:00', max_length=10)),
                ('check_out_time', models.CharField(default='12:00', max_length=10)),
                ('booking_com_url', models.URLField(blank=True, default='', max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='properties/logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('contact', 'Contact'), ('rooms', 'Rooms'), ('location', 'Guest House in F6/2 Islamabad'), ('location_islamabad', 'Guest House in Islamabad'), ('location_near_faisal_mosque', 'Guest House Near Faisal Mosque')], max_length=50),
        ),
        migrations.AddField(
            model_name='faq',
            name='guest_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='core.property'),
        ),
        migrations.AddField(
            model_name='nearbyattraction',
            name='guest_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nearby_attractions', to='core.property'),
        ),
        migrations.AddField(
            model_name='pageseo',
            name='guest_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_seos', to='core.property'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='guest_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='core.property'),
        ),
    ]
