# Generated by Django 5.0.6 on 2026-03-02 16:30

from django.db import migrations


def create_executive_property(apps, schema_editor):
    Property = apps.get_model('core', 'Property')
    Property.objects.get_or_create(
        slug='blue-moon-executive',
        defaults={
            'name': 'Blue Moon Executive',
            'short_name': 'Executive',
            'is_active': True,
            'business_name': 'Blue Moon Executive',
            'street_address': 'Islamabad',
            'locality': 'Islamabad',
            'region': 'Islamabad Capital Territory',
            'postal_code': '44000',
            'country': 'PK',
            'phone': '',
            'email': '',
            'latitude': 33.7294000,
            'longitude': 73.0931000,
            'default_meta_title': 'Blue Moon Executive | Guest House in Islamabad',
            'default_meta_description': 'Blue Moon Executive — comfortable accommodation in Islamabad. Book now, pay at check-in!',
            'currency_symbol': 'PKR',
            'check_in_time': '14:00',
            'check_out_time': '12:00',
        },
    )


def remove_executive_property(apps, schema_editor):
    Property = apps.get_model('core', 'Property')
    Property.objects.filter(slug='blue-moon-executive').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_property_alter_pageseo_page_faq_guest_house_and_more'),
    ]

    operations = [
        migrations.RunPython(create_executive_property, remove_executive_property),
    ]
