# Generated by Django 5.0.6 on 2026-03-02 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_create_blue_moon_executive'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='discount_active',
            field=models.BooleanField(default=False, help_text='Whether the property-wide discount is currently active'),
        ),
        migrations.AddField(
            model_name='property',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount % applied to all rooms at this property (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
