# Generated by Django 5.0.6 on 2026-03-02 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_migrate_role_values'),
        ('core', '0005_property_alter_pageseo_page_faq_guest_house_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='guest_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='core.property'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='guest_house',
            field=models.ForeignKey(blank=True, help_text='Property this staff member is assigned to (null for CEO/guests)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='core.property'),
        ),
    ]
