"""
Django settings for bluemoon project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# =============================================================================
# ENVIRONMENT DETECTION
# =============================================================================
# Detect if we're running on a cloud platform (Render or Railway) or locally
IS_PRODUCTION = os.environ.get('RENDER', '') == 'true' or os.environ.get('RAILWAY_ENVIRONMENT', '') != '' or os.environ.get('VERCEL', '') == '1'


# =============================================================================
# SECURITY
# =============================================================================
# On Render: reads SECRET_KEY from environment variable (safe)
# On local: uses the old insecure key (fine for development)
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-akty4*gqwl!v6b4cys7-k)yi@xc4kq2=c=s!w)fpv_rx6z2@ir')

# On Render: DEBUG off (production)
# On local: DEBUG on (development)
DEBUG = not IS_PRODUCTION

# Production: allow platform URLs
# Local: allow everything
ALLOWED_HOSTS = []
if IS_PRODUCTION:
    RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
    RAILWAY_PUBLIC_DOMAIN = os.environ.get('RAILWAY_PUBLIC_DOMAIN')
    VERCEL_URL = os.environ.get('VERCEL_URL')
    if RENDER_EXTERNAL_HOSTNAME:
        ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    if RAILWAY_PUBLIC_DOMAIN:
        ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)
    if VERCEL_URL:
        ALLOWED_HOSTS.append(VERCEL_URL)
    # Allow all .vercel.app subdomains
    ALLOWED_HOSTS.append('.vercel.app')
    # Fallback: allow all if no specific host detected
    if not ALLOWED_HOSTS:
        ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = ['*']


# =============================================================================
# INSTALLED APPS
# =============================================================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sitemaps',
    'rest_framework',
    'corsheaders',
    'core',
    'accounts',
    'rooms',
    'bookings',
    'api',
]


# =============================================================================
# MIDDLEWARE
# =============================================================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
]
if IS_PRODUCTION:
    MIDDLEWARE.append('whitenoise.middleware.WhiteNoiseMiddleware')
MIDDLEWARE += [
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.PropertyMiddleware',
]

ROOT_URLCONF = 'bluemoon.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.seo_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'bluemoon.wsgi.application'


# =============================================================================
# DATABASE
# =============================================================================
# On Render: reads DATABASE_URL environment variable (PostgreSQL)
# On local: uses SQLite (no change for you)
if IS_PRODUCTION:
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# =============================================================================
# PASSWORD VALIDATION
# =============================================================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# =============================================================================
# INTERNATIONALIZATION
# =============================================================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# =============================================================================
# STATIC FILES
# =============================================================================
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise: serves static files efficiently in production
if IS_PRODUCTION:
    STORAGES = {
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# =============================================================================
# AUTHENTICATION
# =============================================================================
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/accounts/dashboard/'
LOGOUT_REDIRECT_URL = '/'


# =============================================================================
# EMAIL
# =============================================================================
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'Blue Moon Residency <noreply@bluemoonresidency.com>'


# =============================================================================
# MISC
# =============================================================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Site URL (used for canonical URLs, sitemaps, Open Graph)
SITE_URL = 'https://bluemoonresidency.com'

# Caching
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'bluemoon-cache',
    }
}


# =============================================================================
# SECURITY SETTINGS (only on Render/production)
# =============================================================================
if IS_PRODUCTION:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    CSRF_TRUSTED_ORIGINS = []
    if os.environ.get('RENDER_EXTERNAL_HOSTNAME'):
        CSRF_TRUSTED_ORIGINS.append(f'https://{os.environ["RENDER_EXTERNAL_HOSTNAME"]}')
    if os.environ.get('RAILWAY_PUBLIC_DOMAIN'):
        CSRF_TRUSTED_ORIGINS.append(f'https://{os.environ["RAILWAY_PUBLIC_DOMAIN"]}')
    if os.environ.get('VERCEL_URL'):
        CSRF_TRUSTED_ORIGINS.append(f'https://{os.environ["VERCEL_URL"]}')


# =============================================================================
# Django REST Framework
# =============================================================================
from datetime import timedelta

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS
if IS_PRODUCTION:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = []
    if os.environ.get('RENDER_EXTERNAL_HOSTNAME'):
        CORS_ALLOWED_ORIGINS.append(f'https://{os.environ["RENDER_EXTERNAL_HOSTNAME"]}')
    if os.environ.get('RAILWAY_PUBLIC_DOMAIN'):
        CORS_ALLOWED_ORIGINS.append(f'https://{os.environ["RAILWAY_PUBLIC_DOMAIN"]}')
    if os.environ.get('VERCEL_URL'):
        CORS_ALLOWED_ORIGINS.append(f'https://{os.environ["VERCEL_URL"]}')
else:
    CORS_ALLOW_ALL_ORIGINS = True
