# Generated by Django 5.0.6 on 2026-03-02 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_guest_email_booking_guest_name_and_more'),
        ('core', '0005_property_alter_pageseo_page_faq_guest_house_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.property'),
        ),
    ]
